name: 'PGATS - Integração Contínua para Automação de Testes'

on:
  # Disparo manual
  workflow_dispatch:

  # Disparo agendado para rodar todo dia 
  schedule:
    - cron: '0 * * * *'

  # Disparo a partir de push
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest    
    steps:     
      - uses: actions/checkout@v4
    
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando dependências
        run: npm install

      - name: Executando os testes unitários
        run: npm test

      - name: Renomear arquivo de relatório
        run: mv ./mochawesome-report/mochawesome.html ./mochawesome-report/index.html
  
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1        
        with:
          source: ./mochawesome-report
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5